#!/usr/bin/env python3
"""Convert Frida / manual calibration logs into Assist physics JSON."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

DEFAULT = {
    "maxShotPower": 140.0,
    "maxShotSpeed": 28.0,
    "puckMass": 2.0,
    "ballMass": 1.0,
    "friction": 0.985,
    "restitution": 0.92,
    "edgeRestitution": 0.92,
    "powerScale": 1.0,
    "notes": "Generated by parse_calibration.py",
}


def parse_shot_line(line: str) -> dict | None:
    # angle=1.23 power=0.87 puck=2
    m = re.search(
        r"angle\s*[=:]\s*([-\d.]+).*power\s*[=:]\s*([-\d.]+)(?:.*puck\s*[=:]\s*(\d+))?",
        line,
        re.I,
    )
    if not m:
        return None
    return {
        "angle": float(m.group(1)),
        "power": float(m.group(2)),
        "puck": int(m.group(3) or 0),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("log_file", nargs="?", help="Frida or manual log")
    parser.add_argument("-o", "--output", default="physics.json")
    args = parser.parse_args()

    config = dict(DEFAULT)
    shots: list[dict] = []

    if args.log_file and Path(args.log_file).exists():
        for line in Path(args.log_file).read_text(encoding="utf-8", errors="ignore").splitlines():
            if "friction" in line.lower():
                val = re.search(r"([\d.]+)", line)
                if val:
                    config["friction"] = float(val.group(1))
            if "restitution" in line.lower():
                val = re.search(r"([\d.]+)", line)
                if val:
                    config["restitution"] = float(val.group(1))
            shot = parse_shot_line(line)
            if shot:
                shots.append(shot)

    if shots:
        powers = [s["power"] for s in shots if s["power"] > 0]
        if powers:
            config["maxShotPower"] = max(powers) * 1.05
        config["sampleShots"] = shots[:20]

    Path(args.output).write_text(
        json.dumps(config, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
